from models import db, FishSpecies
from app import app

fish_data = [
    {
        "name": "Neon Tetra",
        "min_temp": 20,
        "max_temp": 26,
        "min_ph": 5.0,
        "max_ph": 7.0,
        "min_kh": 1,
        "max_kh": 5,
        "min_gh": 2,
        "max_gh": 10,
        "adult_length": 3.5,
        "image": "neon.jpg",
    },
    {
        "name": "Guppy",
        "min_temp": 22,
        "max_temp": 28,
        "min_ph": 6.5,
        "max_ph": 8.0,
        "min_kh": 4,
        "max_kh": 8,
        "min_gh": 6,
        "max_gh": 12,
        "adult_length": 4.0,
        "image": "guppy.jpg",
    },
    {
        "name": "Red Cherry Shrimp",
        "min_temp": 18,
        "max_temp": 28,
        "min_ph": 6.2,
        "max_ph": 8.0,
        "min_kh": 1,
        "max_kh": 6,
        "min_gh": 4,
        "max_gh": 14,
        "adult_length": 2.5,
        "image": "redcherryshrimp.jpg",
    },
    {
        "name": "Zebra Danio",
        "min_temp": 18,
        "max_temp": 24,
        "min_ph": 6.5,
        "max_ph": 7.5,
        "min_kh": 2,
        "max_kh": 8,
        "min_gh": 5,
        "max_gh": 12,
        "adult_length": 4.5,
        "image": "zebra.jpg",
    },
    {
        "name": "Betta",
        "min_temp": 24,
        "max_temp": 30,
        "min_ph": 6.0,
        "max_ph": 7.5,
        "min_kh": 1,
        "max_kh": 5,
        "min_gh": 3,
        "max_gh": 10,
        "adult_length": 6.0,
        "image": "betta.jpg",
    },
    {
        "name": "Corydoras",
        "min_temp": 22,
        "max_temp": 26,
        "min_ph": 6.0,
        "max_ph": 7.5,
        "min_kh": 2,
        "max_kh": 10,
        "min_gh": 4,
        "max_gh": 12,
        "adult_length": 5.0,
        "image": "corydoras.jpg",
    },
    {
        "name": "Molly",
        "min_temp": 24,
        "max_temp": 28,
        "min_ph": 7.5,
        "max_ph": 8.5,
        "min_kh": 8,
        "max_kh": 12,
        "min_gh": 10,
        "max_gh": 20,
        "adult_length": 6.5,
        "image": "molly.jpg",
    },
    {
        "name": "Swordtail",
        "min_temp": 24,
        "max_temp": 28,
        "min_ph": 7.0,
        "max_ph": 8.4,
        "min_kh": 3,
        "max_kh": 10,
        "min_gh": 8,
        "max_gh": 20,
        "adult_length": 8.0,
        "image": "swordtail.jpg",
    },
    {
        "name": "Dwarf Gourami",
        "min_temp": 24,
        "max_temp": 28,
        "min_ph": 6.0,
        "max_ph": 7.5,
        "min_kh": 2,
        "max_kh": 8,
        "min_gh": 4,
        "max_gh": 10,
        "adult_length": 7.0,
        "image": "gourami.jpg",
    },
    {
        "name": "Otocinclus",
        "min_temp": 21,
        "max_temp": 26,
        "min_ph": 6.0,
        "max_ph": 7.5,
        "min_kh": 1,
        "max_kh": 5,
        "min_gh": 3,
        "max_gh": 10,
        "adult_length": 4.0,
        "image": "otocinclus.jpg",
    },
    {
        "name": "Harlequin Rasbora",
        "min_temp": 22,
        "max_temp": 28,
        "min_ph": 6.0,
        "max_ph": 7.5,
        "min_kh": 2,
        "max_kh": 8,
        "min_gh": 4,
        "max_gh": 12,
        "adult_length": 4.5,
        "image": "rasbora.jpg",
    },
    {
        "name": "Pearl Gourami",
        "min_temp": 24,
        "max_temp": 28,
        "min_ph": 6.5,
        "max_ph": 8.0,
        "min_kh": 3,
        "max_kh": 10,
        "min_gh": 5,
        "max_gh": 15,
        "adult_length": 10.0,
        "image": "pearlgourami.jpg",
    },
    {
        "name": "Bristlenose Pleco",
        "min_temp": 22,
        "max_temp": 28,
        "min_ph": 6.5,
        "max_ph": 7.5,
        "min_kh": 3,
        "max_kh": 8,
        "min_gh": 6,
        "max_gh": 12,
        "adult_length": 12.0,
        "image": "bristlenose.jpg",
    },
    {
        "name": "Endler's Livebearer",
        "min_temp": 22,
        "max_temp": 28,
        "min_ph": 6.5,
        "max_ph": 8.0,
        "min_kh": 3,
        "max_kh": 8,
        "min_gh": 5,
        "max_gh": 12,
        "adult_length": 3.0,
        "image": "endler.jpg",
    },
]

with app.app_context():
    for fish in fish_data:
        existing = FishSpecies.query.filter_by(name=fish["name"]).first()
        if existing:
            # 🔁 Aktualizuj dane
            for key, value in fish.items():
                setattr(existing, key, value)
            print(f"Updated {fish['name']}")
        else:
            # ➕ Dodaj nowy wpis
            new_fish = FishSpecies(**fish)
            db.session.add(new_fish)
            print(f"Added {fish['name']}")
    db.session.commit()
    print("✅ Fish database updated.")
