"""Add Tank model

Revision ID: 426316aaa988
Revises: c03ad3dd09eb
Create Date: 2025-06-14 15:52:26.832047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426316aaa988'
down_revision = 'c03ad3dd09eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('volume',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('temperature',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('ph',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('kh')
        batch_op.drop_column('image_filename')
        batch_op.drop_column('description')
        batch_op.drop_column('gh')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gh', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('kh', sa.FLOAT(), nullable=False))
        batch_op.alter_column('ph',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('temperature',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('volume',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
