"""Add daily_checks to Tank

Revision ID: 5215be1f3cf0
Revises: e68e9cdb36f8
Create Date: 2025-06-17 09:32:05.940150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5215be1f3cf0'
down_revision = 'e68e9cdb36f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_checks', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.drop_column('daily_checks')

    # ### end Alembic commands ###
