"""Add ImportantTask model

Revision ID: 8213bfe71924
Revises: ea7a6ee7e88c
Create Date: 2025-06-17 14:48:52.509093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8213bfe71924'
down_revision = 'ea7a6ee7e88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.drop_column('important_tasks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('important_tasks', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
