"""Add FishStock table

Revision ID: accbed7b83b9
Revises: e68e9cdb36f8
Create Date: 2025-06-18 11:33:02.022110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'accbed7b83b9'
down_revision = 'e68e9cdb36f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fish')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fish',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('species', sa.VARCHAR(length=100), nullable=True),
    sa.Column('count', sa.INTEGER(), nullable=False),
    sa.Column('image', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tank_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['tank_id'], ['tank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
