"""Add kh, gh, description, image to Tank

Revision ID: c7df6cefeffa
Revises: 426316aaa988
Create Date: 2025-06-14 16:45:42.461571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7df6cefeffa'
down_revision = '426316aaa988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kh', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gh', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('description')
        batch_op.drop_column('gh')
        batch_op.drop_column('kh')

    # ### end Alembic commands ###
